export const FETCH_POPULARMOVIE_START = "FETCH_POPULARMOVIE_START";
export const FETCH_POPULARMOVIE_SUCC = "FETCH_POPULARMOVIE_SUCC";
export const FETCH_POPULARMOVIE_FAIELD = "FETCH_POPULARMOVIE_FAIELD";